// src/views/Func/index.tsx
import { useEffect, useState } from 'react';
import { CurrentTime, getCurrentTime } from '@/utils/getTime';
import Hitokoto from '@/components/Hitokoto';

export default function Func() {
  const [currentTime, setCurrentTime] = useState<CurrentTime>(getCurrentTime());

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTime(getCurrentTime());
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="flex flex-row items-center h-41.25 justify-between w-full">
      <div className="flex-1 p-1 w-full h-full">
        <Hitokoto />
      </div>
      <div className="flex-1 p-1 max-w-[calc(50%-10px)] w-full h-full">
        <div className="w-full h-full cards p-5 flex flex-col items-center justify-between animate-fade">
          <div className="text-center text-[1.1rem] max-[1280px]:text-base max-[992px]:text-sm">
            <div className="text-ellipsis overflow-x-hidden whitespace-nowrap">
              <span>{currentTime.year}&nbsp;年&nbsp;</span>
              <span>{currentTime.month}&nbsp;月&nbsp;</span>
              <span>{currentTime.day}&nbsp;日&nbsp;</span>
              <span className="max-[910px]:hidden">{currentTime.weekday}</span>
            </div>
            <div className="mt-2.5 text-[3.25rem] tracking-[2px] max-[1280px]:text-[2.75rem] max-[992px]:text-[2.5rem]">
              <span> {currentTime.hour}:{currentTime.minute}:{currentTime.second}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/views/Func/index.vue
<template>
  <!-- 功能区域 -->
  <div :class="store.mobileFuncState ? 'function mobile' : 'function'">
    <CustomRow :gutter="20">
      <CustomCol :span="12">
        <div class="left">
          <Hitokoto />
        </div>
      </CustomCol>
      <CustomCol :span="12">
        <div class="right cards">
          <div class="time">
            <div class="date">
              <span>{{ currentTime.year }}&nbsp;年&nbsp;</span>
              <span>{{ currentTime.month }}&nbsp;月&nbsp;</span>
              <span>{{ currentTime.day }}&nbsp;日&nbsp;</span>
              <span class="sm-hidden">{{ currentTime.weekday }}</span>
            </div>
            <div class="text">
              <span> {{ currentTime.hour }}:{{ currentTime.minute }}:{{ currentTime.second }}</span>
            </div>
          </div>
        </div>
      </CustomCol>
    </CustomRow>
  </div>
</template>

<script setup>
import { getCurrentTime } from "@/utils/getTime";
import { mainStore } from "@/store";
import Hitokoto from "@/components/Hitokoto.vue";
import CustomRow from "@/components/custom/Row.vue";
import CustomCol from "@/components/custom/Col.vue";

const store = mainStore();

// 当前时间
const currentTime = ref({});
const timeInterval = ref(null);


// 更新时间
const updateTimeData = () => {
  currentTime.value = getCurrentTime();
};

onMounted(() => {
  updateTimeData();
  timeInterval.value = setInterval(updateTimeData, 1000);
});

onBeforeUnmount(() => {
  clearInterval(timeInterval.value);
});
</script>

<style lang="scss" scoped>
.function {
  height: 165px;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;

  &.mobile {
    .custom-row {
      .custom-col {
        &:nth-of-type(1) {
          display: contents;
        }

        &:nth-of-type(2) {
          display: none;
        }
      }
    }
  }

  .custom-row {
    height: 100%;
    width: 100%;

    .custom-col {
      &:nth-of-type(1) {
        padding-left: 0 !important;
      }

      &:nth-of-type(2) {
        padding-right: 0 !important;
      }

      @media (max-width: 910px) {
        &:nth-of-type(1) {
          display: none;
        }

        &:nth-of-type(2) {
          padding: 0 !important;
          flex: none;
          max-width: none;
          width: 100%;
        }
      }
    }

    .left,
    .right {
      width: 100%;
      height: 100%;
    }

    .right {
      padding: 20px;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: space-between;
      animation: fade 0.5s;

      .time {
        font-size: 1.1rem;
        text-align: center;

        .date {
          text-overflow: ellipsis;
          overflow-x: hidden;
          white-space: nowrap;
        }

        .text {
          margin-top: 10px;
          font-size: 3.25rem;
          letter-spacing: 2px;
          font-family: "UnidreamLED";
        }

        @media (min-width: 1201px) and (max-width: 1280px) {
          font-size: 1rem;
        }

        @media (min-width: 911px) and (max-width: 992px) {
          font-size: 1rem;

          .text {
            font-size: 2.75rem;
          }
        }
      }

    }
  }
}
</style>
