// src/components/Background.tsx
import { useEffect, useState } from 'react';
import { useMainStore } from '@/store';
import { Error } from '@icon-park/react';
import ElMessage from '@/components/custom/message';
import { cn } from '@/utils/cn';
import styles from './Background.module.scss';

interface BackgroundProps {
  onLoadComplete?: () => void;
}

export default function Background({ onLoadComplete }: BackgroundProps) {
  const bgUrl = useMainStore((state) => state.coverType);
  const backgroundShow = useMainStore((state) => state.backgroundShow);
  const imgLoadStatus = useMainStore((state) => state.imgLoadStatus);
  const setImgLoadStatus = useMainStore((state) => state.setImgLoadStatus);
  const setCoverType = useMainStore((state) => state.setCoverType);

  const [bgUrlValue, setBgUrlValue] = useState('');
  const [imgTimeoutValue, setImgTimeoutValue] = useState<NodeJS.Timeout | null>(null);

  const bgRandom = Math.floor(Math.random() * 10 + 1);

  const changeBg = (type: string) => {
    if (type == '0') {
      setBgUrlValue(`/images/background${bgRandom}.jpg`);
    } else if (type == '1') {
      setBgUrlValue('https://api.dujin.org/bing/1920.php');
    } else if (type == '2') {
      setBgUrlValue('https://api.vvhan.com/api/wallpaper/views');
    } else if (type == '3') {
      setBgUrlValue('https://api.vvhan.com/api/wallpaper/acg');
    }
  };

  useEffect(() => {
    changeBg(bgUrl);
  }, [bgUrl]);

  const imgLoadComplete = () => {
    const timeout = setTimeout(
      () => {
        setImgLoadStatus(true);
      },
      Math.floor(Math.random() * (600 - 300 + 1)) + 300
    );
    setImgTimeoutValue(timeout);
  };

  const imgAnimationEnd = () => {
    console.log('壁纸加载且动画完成');
    onLoadComplete?.();
  };

  const imgLoadError = () => {
    console.error('壁纸加载失败：', bgUrlValue);
    ElMessage({
      message: '壁纸加载失败,已临时切换回默认',
      icon: h(Error, {
        theme: 'filled',
        fill: '#efefef'
      })
    });
    setBgUrlValue(`/images/background${bgRandom}.jpg`);
  };

  useEffect(() => {
    return () => {
      if (imgTimeoutValue) {
        clearTimeout(imgTimeoutValue);
      }
    };
  }, [imgTimeoutValue]);

  return (
    <div className={cn(styles.cover, 'absolute top-0 left-0 w-full h-full transition-all z-[-1]', backgroundShow && styles.show)}>
      <img
        src={bgUrlValue}
        className={cn(styles.bg, 'absolute top-0 left-0 w-full h-full object-cover')}
        alt="cover"
        onLoad={imgLoadComplete}
        onError={imgLoadError}
        onAnimationEnd={imgAnimationEnd}
      />
    </div>
  );
}

// src/components/Background.vue
<template>
  <div :class="store.backgroundShow ? 'cover show' : 'cover'">
    <img
      v-show="store.imgLoadStatus"
      :src="bgUrl"
      class="bg"
      alt="cover"
      @load="imgLoadComplete"
      @error.once="imgLoadError"
      @animationend="imgAnimationEnd"
    />
    <div :class="store.backgroundShow ? 'gray hidden' : 'gray'" />
    <Transition name="fade" mode="out-in">
      <a
        v-if="store.backgroundShow && store.coverType != '3'"
        class="down"
        :href="bgUrl"
        target="_blank"
      >
        下载壁纸
      </a>
    </Transition>
  </div>
</template>

<script setup>
import { mainStore } from "@/store";
import { Error } from "@icon-park/vue-next";
import ElMessage from "@/components/custom/message";

const store = mainStore();
const bgUrl = ref(null);
const imgTimeout = ref(null);
const emit = defineEmits(["loadComplete"]);

// 壁纸随机数
// 请依据文件夹内的图片个数修改 Math.random() 后面的第一个数字
const bgRandom = Math.floor(Math.random() * 10 + 1);

// 更换壁纸链接
const changeBg = (type) => {
  if (type == 0) {
    bgUrl.value = `/images/background${bgRandom}.jpg`;
  } else if (type == 1) {
    bgUrl.value = "https://api.dujin.org/bing/1920.php";
  } else if (type == 2) {
    bgUrl.value = "https://api.vvhan.com/api/wallpaper/views";
  } else if (type == 3) {
    bgUrl.value = "https://api.vvhan.com/api/wallpaper/acg";
  }
};

// 图片加载完成
const imgLoadComplete = () => {
  imgTimeout.value = setTimeout(
    () => {
      store.setImgLoadStatus(true);
    },
    Math.floor(Math.random() * (600 - 300 + 1)) + 300,
  );
};

// 图片动画完成
const imgAnimationEnd = () => {
  console.log("壁纸加载且动画完成");
  // 加载完成事件
  emit("loadComplete");
};

// 图片显示失败
const imgLoadError = () => {
  console.error("壁纸加载失败：", bgUrl.value);
  ElMessage({
    message: "壁纸加载失败，已临时切换回默认",
    icon: h(Error, {
      theme: "filled",
      fill: "#efefef",
    }),
  });
  bgUrl.value = `/images/background${bgRandom}.jpg`;
};

// 监听壁纸切换
watch(
  () => store.coverType,
  (value) => {
    changeBg(value);
  },
);

onMounted(() => {
  // 加载壁纸
  changeBg(store.coverType);
});

onBeforeUnmount(() => {
  clearTimeout(imgTimeout.value);
});
</script>

<style lang="scss" scoped>
.cover {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  transition: 0.25s;
  z-index: -1;

  &.show {
    z-index: 1;
  }

  .bg {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
    backface-visibility: hidden;
    filter: blur(20px) brightness(0.3);
    transition:
      filter 0.3s,
      transform 0.3s;
    animation: fade-blur-in 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) forwards;
    animation-delay: 0.45s;
  }
  .gray {
    opacity: 1;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-image: radial-gradient(rgba(0, 0, 0, 0) 0, rgba(0, 0, 0, 0.5) 100%),
      radial-gradient(rgba(0, 0, 0, 0) 33%, rgba(0, 0, 0, 0.3) 166%);

    transition: 1.5s;
    &.hidden {
      opacity: 0;
      transition: 1.5s;
    }
  }
  .down {
    font-size: 16px;
    color: white;
    position: absolute;
    bottom: 30px;
    left: 0;
    right: 0;
    margin: 0 auto;
    display: block;
    padding: 20px 26px;
    border-radius: 8px;
    background-color: #00000030;
    width: 120px;
    height: 30px;
    display: flex;
    justify-content: center;
    align-items: center;
    &:hover {
      transform: scale(1.05);
      background-color: #00000060;
    }
    &:active {
      transform: scale(1);
    }
  }
}
</style>
