// src/components/Footer.tsx
import { useMainStore } from '@/store';
import { cn } from '@/utils/cn';
import styles from './Footer.module.scss';

export default function Footer({ className }: { className?: string }) {
  const fullYear = new Date().getFullYear();
  const startYear = import.meta.env.VITE_SITE_START?.length >= 4
    ? import.meta.env.VITE_SITE_START.substring(0, 4)
    : null;
  const siteIcp = import.meta.env.VITE_SITE_ICP;
  const siteAuthor = import.meta.env.VITE_SITE_AUTHOR;
  const siteUrl = import.meta.env.VITE_SITE_URL;
  
  const getSiteUrl = () => {
    if (!siteUrl.startsWith('http://') && !siteUrl.startsWith('https://')) {
      return '//' + siteUrl;
    }
    return siteUrl;
  };

  return (
    <footer className={cn(styles.footer, 'absolute bottom-0 left-0 w-full h-11.5 text-center z-0 text-sm break-keep whitespace-nowrap', className, styles.blur)}>
      <div className={cn(styles.power, 'animation-fade duration-300')}>
        <span>
          <span className={cn(Number(startYear) < fullYear ? styles.cHidden : styles.hidden, 'hidden lg:block')}>Copyright&nbsp;&nbsp;</span>
          &copy;
          {Number(startYear) < fullYear && (
            <span className={styles.siteStart}>
              {startYear}-
            </span>
          )}
          {fullYear}&nbsp;&nbsp;
          <a href={getSiteUrl()}>{siteAuthor}</a>
        </span>
        {siteIcp && (
          <span>
            &amp;
            <a href="https://beian.miit.gov.cn" target="_blank">
              {siteIcp}
            </a>
          </span>
        )}
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer id="footer" :class="store.footerBlur ? 'blur' : null">
    <Transition name="fade" mode="out-in">
      <div class="power">
        <span>
          <span :class="startYear < fullYear ? 'c-hidden' : 'hidden'">Copyright&nbsp;</span>
          &copy;
          <span v-if="startYear < fullYear"
            class="site-start">
            {{ startYear }}
            -
          </span>
          {{ fullYear }}
          <a :href="siteUrl">{{ siteAuthor }}</a>
        </span>
        <!-- 站点备案 -->
        <span v-if="siteIcp">
          &amp;
          <a href="https://beian.miit.gov.cn" target="_blank">
            {{ siteIcp }}
          </a>
        </span>
      </div>
    </Transition>
  </footer>
</template>

<script setup>
import { mainStore } from "@/store";
import config from "@/../package.json";

const store = mainStore();
const fullYear = new Date().getFullYear();

// 加载配置数据
// const siteStartDate = ref(import.meta.env.VITE_SITE_START);
const startYear = ref(
  import.meta.env.VITE_SITE_START?.length >= 4 ? 
  import.meta.env.VITE_SITE_START.substring(0, 4) : null
);
const siteIcp = ref(import.meta.env.VITE_SITE_ICP);
const siteAuthor = ref(import.meta.env.VITE_SITE_AUTHOR);
const siteUrl = computed(() => {
  const url = import.meta.env.VITE_SITE_URL;
  if (!url) return "https://www.imsyy.top";
  // 判断协议前缀
  if (!url.startsWith("http://") && !url.startsWith("https://")) {
    return "//" + url;
  }
  return url;
});
</script>

<style lang="scss" scoped>
#footer {
  width: 100%;
  position: absolute;
  bottom: 0;
  left: 0;
  height: 46px;
  line-height: 46px;
  text-align: center;
  z-index: 0;
  font-size: 14px;
  // 文字不换行
  word-break: keep-all;
  white-space: nowrap;
  .power {
    animation: fade 0.3s;
  }
  .lrc {
    padding: 0 20px;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    .lrc-all {
      width: 98%;
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      .lrc-text {
        margin: 0 8px;
      }
      .i-icon {
        width: 18px;
        height: 18px;
        display: inherit;
      }
    }
  }
  &.blur {
    backdrop-filter: blur(10px);
    background: rgb(0 0 0 / 25%);
    font-size: 16px;
  }
  .fade-enter-active,
  .fade-leave-active {
    transition: opacity 0.15s ease-in-out;
  }
  @media (max-width: 720px) {
    font-size: 0.9rem;
    &.blur {
      font-size: 0.9rem;
    }
  }
  @media (max-width: 560px) {
    .c-hidden {
      display: none;
    }
  }
  @media (max-width: 480px) {
    .hidden {
      display: none;
    }
  }
}
</style>
