// src/components/Message.tsx
import { useMainStore } from '@/store';
import { cn } from '@/utils/cn';
import styles from './Message.module.scss';
import { Icon } from '@iconify/react';

export default function Message() {
  const boxOpenState = useMainStore((state) => state.boxOpenState);
  const siteLogo = import.meta.env.VITE_SITE_MAIN_LOGO;
  const siteAuthor = import.meta.env.VITE_SITE_AUTHOR;
  
  const getSiteUrl = () => {
    if (siteAuthor.startsWith('http://') || siteAuthor.startsWith('https://')) {
      return siteAuthor.replace(/^(https?:\/\/)/, '').split('.');
    }
    return siteAuthor.split('.');
  };
  const urlParts = getSiteUrl();

  const descriptionText = {
    hello: import.meta.env.VITE_DESC_HELLO,
    text: import.meta.env.VITE_DESC_TEXT,
  };

  const displayText = boxOpenState ? {
    hello: import.meta.env.VITE_DESC_HELLO_OTHER,
    text: import.meta.env.VITE_DESC_TEXT_OTHER,
  } : descriptionText;

  return (
    <>
      <div className={cn(styles.logo, 'flex flex-row items-center animation-fade max-w-115')}>
        <img className={cn(styles.logoImg, 'rounded-full w-28')} src={siteLogo} alt="logo" />
        <div className={cn(styles.name, 'text-hidden w-full pl-5.5 -translate-y-2', urlParts[0].length >= 6 && styles.long)}>
          <span className={cn(styles.bg, 'text-5xl')}>{urlParts[0]}</span>
          <span className={cn(styles.sm, 'ml-1.5 text-2xl')}>{urlParts[1]}</span>
        </div>
      </div>
      <div className={cn(styles.description, 'cards p-4! mt-14! max-w-115')}>
        <div className={cn(styles.content, 'flex justify-between')}>
          <Icon icon="fa:quote-left" height={16} width={16} />
          <div className={cn(styles.text, 'my-3 mx-4 leading-8 mr-auto')}>
            <p>{displayText.text}</p>
          </div>
          <Icon icon="fa:quote-right" height={16} width={16} />
        </div>
      </div>
    </>
  );
}

// src/components/Message.vue
<template>
  <!-- 基本信息 -->
  <div class="message">
    <!-- Logo -->
    <div class="logo">
      <img class="logo-img" :src="siteLogo" alt="logo" />
      <div :class="{ name: true, 'text-hidden': true, long: siteUrl[0].length >= 6 }">
        <span class="bg">{{ siteUrl[0] }}</span>
        <span class="sm">.{{ siteUrl[1] }}</span>
      </div>
    </div>
    <!-- 简介 -->
    <div class="description cards" @click="changeBox">
      <div class="content">
        <Icon size="16">
          <QuoteLeft />
        </Icon>
        <Transition name="fade" mode="out-in">
          <div :key="descriptionText.hello + descriptionText.text" class="text">
            <p>{{ descriptionText.hello }}</p>
            <p>{{ descriptionText.text }}</p>
          </div>
        </Transition>
        <Icon size="16">
          <QuoteRight />
        </Icon>
      </div>
    </div>
  </div>
</template>

<script setup>
import { Icon } from "@vicons/utils";
import { QuoteLeft, QuoteRight } from "@vicons/fa";
import { Error } from "@icon-park/vue-next";
import { mainStore } from "@/store";
const store = mainStore();

// 主页站点logo
const siteLogo = import.meta.env.VITE_SITE_MAIN_LOGO;
// 站点链接
const siteUrl = computed(() => {
  const url = import.meta.env.VITE_SITE_AUTHOR;
  if (!url) return "imsyy.top".split(".");
  // 判断协议前缀
  if (url.startsWith("http://") || url.startsWith("https://")) {
    const urlFormat = url.replace(/^(https?:\/\/)/, "");
    return urlFormat.split(".");
  }
  return url.split(".");
});

// 简介区域文字
const descriptionText = reactive({
  hello: import.meta.env.VITE_DESC_HELLO,
  text: import.meta.env.VITE_DESC_TEXT,
});

// 切换右侧功能区
const changeBox = () => {
  if (store.getInnerWidth >= 721) {
    store.boxOpenState = !store.boxOpenState;
  } else {
    ElMessage({
      message: "当前页面宽度不足以开启盒子",
      grouping: true,
      icon: h(Error, {
        theme: "filled",
        fill: "#efefef",
      }),
    });
  }
};

// 监听状态变化
watch(
  () => store.boxOpenState,
  (value) => {
    if (value) {
      descriptionText.hello = import.meta.env.VITE_DESC_HELLO_OTHER;
      descriptionText.text = import.meta.env.VITE_DESC_TEXT_OTHER;
    } else {
      descriptionText.hello = import.meta.env.VITE_DESC_HELLO;
      descriptionText.text = import.meta.env.VITE_DESC_TEXT;
    }
  },
);
</script>

<style lang="scss" scoped>
.message {
  .logo {
    display: flex;
    flex-direction: row;
    align-items: center;
    animation: fade 0.5s;
    max-width: 460px;

    .logo-img {
      border-radius: 50%;
      width: 120px;
    }

    .name {
      width: 100%;
      padding-left: 22px;
      transform: translateY(-8px);
      font-family: "Pacifico-Regular";

      .bg {
        font-size: 5rem;
      }

      .sm {
        margin-left: 6px;
        font-size: 2rem;

        @media (min-width: 721px) and (max-width: 789px) {
          display: none;
        }
      }
    }

    @media (max-width: 768px) {
      .logo-img {
        width: 100px;
      }

      .name {
        height: 128px;

        .bg {
          font-size: 4.5rem;
        }
      }
    }

    @media (max-width: 720px) {
      max-width: 100%;
    }
  }

  .description {
    padding: 1rem;
    margin-top: 3.5rem;
    max-width: 460px;
    animation: fade 0.5s;

    .content {
      display: flex;
      justify-content: space-between;

      .text {
        margin: 0.75rem 1rem;
        line-height: 2rem;
        margin-right: auto;
        transition: opacity 0.2s;

        p {
          &:nth-of-type(1) {
            font-family: "Pacifico-Regular";
          }
        }
      }

      .xicon:nth-of-type(2) {
        align-self: flex-end;
      }
    }

    @media (max-width: 720px) {
      max-width: 100%;
      pointer-events: none;
    }
  }

  // @media (max-width: 390px) {
  //   .logo {
  //     flex-direction: column;
  //     .logo-img {
  //       display: none;
  //     }
  //     .name {
  //       margin-left: 0;
  //       height: auto;
  //       transform: none;
  //       text-align: center;
  //       .bg {
  //         font-size: 3.5rem;
  //       }
  //       .sm {
  //         font-size: 1.4rem;
  //       }
  //     }
  //   }
  //   .description {
  //     margin-top: 2.5rem;
  //   }
  // }
}
</style>
