// src/views/Main/Left.tsx
import { useMainStore } from '@/store';
import { cn } from '@/utils/cn';
import styles from './Left.module.scss';

export default function MainLeft() {
  const mobileOpenState = useMainStore((state) => state.mobileOpenState);
  const boxOpenState = useMainStore((state) => state.boxOpenState);

  return (
    <div className={cn(styles.left, mobileOpenState && !boxOpenState && styles.hidden)}>
      <Message />
      <SocialLinks />
    </div>
  );
}

import Message from '@/components/Message';
import SocialLinks from '@/components/SocialLinks';

// src/views/Main/Left.vue
<template>
  <div :class="store.mobileOpenState ? 'left hidden' : 'left'">
    <Message />
    <SocialLinks />
  </div>
</template>

<script setup>
import { mainStore } from "@/store";
import Message from "@/components/Message.vue";
import SocialLinks from "@/components/SocialLinks.vue";
const store = mainStore();
</script>

<style lang="scss" scoped>
.left {
  // flex: 1 0 0%;
  width: 50%;
  margin-right: 10px;
  transform: translateY(20px);

  &.hidden {
    display: none;
  }

  @media (max-width: 720px) {
    margin-right: 0;
    width: 100%;
  }
}
</style>
